### PR TITLE
Who knows right now. 

### PR DESCRIPTION
**Pull request by nabobalis**
Basically rebased from astropy-cookiecutter branch.

### CODE REVIEW

**Comment by Cadair** [comment]
looks reasonable to me. we should enable Travis on this repo, and take another pass through the code to make it full sunpy.

**Comment by Cadair** [comment]
oh also, we should pull in the sunpy sphinx theme stuff here.

**Comment by nabobalis** [comment]
Go to sleep but yes.

**Comment by Cadair** [comment]
jet lag says no.

**Pull request merged**
