### PR TITLE
Removes non-existent key for the licence field

### PR DESCRIPTION
**Pull request by nabobalis**

### CODE REVIEW

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
It is indeed not in the spec: https://packaging.python.org/en/latest/specifications/pyproject-toml/#license

**Comment by Cadair** [comment]
This might need to be upstreamed

**Comment by nabobalis** [comment]
I can do that.

**Comment by nabobalis** [comment]
https://github.com/OpenAstronomy/packaging-guide/pull/74

**Pull request merged**
